# Copyright (c) 2026 Abe Kohandel
# SPDX-License-Identifier: MIT

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: "ci"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64le]
    container:
      image: ghcr.io/kodebooth/qnx-sdp:latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          set -e
          apt-get update
          apt-get install -y --no-install-recommends meson
          . /opt/qnx800/qnx-sdp.sh
          meson setup --cross-file cross-nto${{ matrix.arch }}.ini build -Dtests=disabled -Dc_args="-DMAX=max -DMIN=min"
          meson compile -C build
